
### Login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "jiesoul",
    "password": "12345678"
}

### logout

POST http://localhost:3000/api/v1/logout
Content-Type: application/json
Authorization: Token 5fcef46a427200a36df72104e7711ef663db7d9b1a375b0bced85aa62cef64b1

### get users

GET http://localhost:3000/api/v1/users/
Content-Type: application/json
Authorization: Token 5fcef46a427200a36df72104e7711ef663db7d9b1a375b0bced85aa62cef64b1