
### Login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "jiesoul",
    "password": "12345678"
}

### logout

POST http://127.0.0.1:3000/api/v1/logout
Content-Type: application/json
Authorization: Token 754b2a1d96fcf7a0ff97f7a049f2f5aebbf8c6d36d360d605a6c0dcf1cec5f92

### get users

GET http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Token a5427f8e694977d84e3afef9b7614ec22c10f7366b65fea13d11f0355d4b1a5b


curl -X 'GET' 'http://127.0.0.1:3000/api/v1/users' -H 'accept: application/json' -H 'authorization: Token d0d63c900a606189c59f71edd7f9e8ba13515e515cafb78f091bb3325b35f718'